#!/bin/bash

set -e

HERE=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
IMAGE_NAME="stream-watch-test"

pushd "$HERE"

for x in cjs esm; do
  docker build -f "$HERE/integration-tests/$x/Dockerfile" -t "$IMAGE_NAME:$x" .
  docker run --rm -it "$IMAGE_NAME:$x"
done

popd